# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from .async_base_client_no_upload import AsyncBaseClient
from .create_user import CreateUser
from .get_user import GetUser
from .input_types import CreateUserInput


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_user(self, id: str, **kwargs: Any) -> GetUser:
        query = gql("""
            query GetUser($id: ID!) {
              user(id: $id) {
                id
                name
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="GetUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUser.model_validate(data)

    async def create_user(self, input: CreateUserInput, **kwargs: Any) -> CreateUser:
        query = gql("""
            mutation CreateUser($input: CreateUserInput!) {
              createUser(input: $input) {
                id
                name
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateUser", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateUser.model_validate(data)
